-- Migration generated by prisma migrate diff (init_complete_schema)
-- WARNING: review carefully before applying to production

-- DropForeignKey
ALTER TABLE "Brand" DROP CONSTRAINT "Brand_orgId_fkey";

-- DropForeignKey
ALTER TABLE "User" DROP CONSTRAINT "User_orgId_fkey";

-- DropForeignKey
ALTER TABLE "User" DROP CONSTRAINT "User_activeBrandId_fkey";

-- DropForeignKey
ALTER TABLE "PhoneNumber" DROP CONSTRAINT "PhoneNumber_brandId_fkey";

-- DropForeignKey
ALTER TABLE "Campaign" DROP CONSTRAINT "Campaign_brandId_fkey";

-- DropForeignKey
ALTER TABLE "Campaign" DROP CONSTRAINT "Campaign_userId_fkey";

-- DropForeignKey
ALTER TABLE "Message" DROP CONSTRAINT "Message_brandId_fkey";

-- DropForeignKey
ALTER TABLE "Message" DROP CONSTRAINT "Message_contactId_fkey";

-- DropForeignKey
ALTER TABLE "CallLog" DROP CONSTRAINT "CallLog_brandId_fkey";

-- DropForeignKey
ALTER TABLE "CallLog" DROP CONSTRAINT "CallLog_contactId_fkey";

-- DropForeignKey
ALTER TABLE "Contact" DROP CONSTRAINT "Contact_brandId_fkey";

-- DropForeignKey
ALTER TABLE "Contact" DROP CONSTRAINT "Contact_assignedNumberId_fkey";

-- DropForeignKey
ALTER TABLE "CustomFieldDefinition" DROP CONSTRAINT "CustomFieldDefinition_brandId_fkey";

-- DropForeignKey
ALTER TABLE "ContactCustomField" DROP CONSTRAINT "ContactCustomField_contactId_fkey";

-- DropForeignKey
ALTER TABLE "ContactCustomField" DROP CONSTRAINT "ContactCustomField_fieldDefinitionId_fkey";

-- DropIndex
DROP INDEX "Contact_brandId_idx";

-- DropIndex
DROP INDEX "Contact_brandId_phoneNumber_key";

-- AlterTable
ALTER TABLE "Contact" DROP COLUMN "aiScore",
DROP COLUMN "assignedNumberId",
DROP COLUMN "brandId",
DROP COLUMN "lineType1",
DROP COLUMN "lineType2",
DROP COLUMN "lineType3",
DROP COLUMN "mailingAddress",
DROP COLUMN "mailingCity",
DROP COLUMN "mailingState",
DROP COLUMN "mailingZip",
DROP COLUMN "phone1",
DROP COLUMN "phone2",
DROP COLUMN "phone3",
DROP COLUMN "phoneNumber",
DROP COLUMN "propertyAddress",
DROP COLUMN "propertyCity",
DROP COLUMN "propertyCounty",
DROP COLUMN "propertyState",
DROP COLUMN "propertyZip",
DROP COLUMN "status",
DROP COLUMN "updatedAt",
ADD COLUMN     "email" TEXT,
ADD COLUMN     "lastActivity" TIMESTAMP(3),
ADD COLUMN     "phone" TEXT;

-- DropTable
DROP TABLE "Organization";

-- DropTable
DROP TABLE "Brand";

-- DropTable
DROP TABLE "User";

-- DropTable
DROP TABLE "PhoneNumber";

-- DropTable
DROP TABLE "Campaign";

-- DropTable
DROP TABLE "Message";

-- DropTable
DROP TABLE "CallLog";

-- DropTable
DROP TABLE "CustomFieldDefinition";

-- DropTable
DROP TABLE "ContactCustomField";
